[workspace]
resolver = "3"
members = [
  "curve_fitter",
  "web-demo"
]

[workspace.dependencies]
clap = { version = "4.0", features = ["derive"] }
kurbo = {version = "0.13.0", features = ["std","serde"] }

